### ISSUE TITLE
Update Asset

### ISSUE THREAD

**Issue by ilrein** [MONEI/Shopify-api-node#131]
Hey, thanks for this library!

I noticed there are tests for updating assets, and I can successfully GET an asset -- but I can't update a liquid template programmatically:

```
/**
   * Update an product page
   * @type {Shopify}
   * @param Number {ThemeId}
   */
  app.post('/api/theme/:themeId/asset/update', (req, res) => {
    const shopify = new Shopify({ shopName: `${req.body.shopName}`, accessToken: req.body.accessToken });

    shopify.asset.update(req.body.themeId, {
      asset: {
        key: 'sections/product-template.liquid',
        value: req.body.value
      }
    })
      .then(assets => res.json({ result: assets }))
      .catch(err => console.error(err));
  });
```

Response is something like:

```
{ HTTPError: Response code 406 (Not Acceptable)
    at stream.catch.then.data (/Users/lreingold/projects/github/pricing_table/node_modules/got/index.js:182:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
  name: 'HTTPError',
  host: undefined,
  hostname: 'easy-tiles-easy-life.myshopify.com',
  method: 'PUT',
  path: '/admin/themes/178721941/assets.json',
  protocol: 'https:',
  url: undefined,
  statusCode: 406,
  statusMessage: 'Not Acceptable',
  headers: 
```

I can definitely GET this asset -- I just can't update it and send it back. Any ideas? My request code: 

```
fetch(`/api/theme/${themeId}/asset/update`, {
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      method: 'POST',
      body: JSON.stringify({ shopName, accessToken, themeId, value: injectedTemplate })
    })
    .then(data => data.json())
    .then(json => console.log(json))
    .catch(e => console.log(e))
```

**Comment by ilrein** [comment]
I also tried using the 'create' method, as the update method is really just the create method -- neither work.

**Comment by lpinca** [comment]
Use this:

```js
shopify.asset.update(req.body.themeId, {
  key: 'sections/product-template.liquid',
  value: req.body.value
})
```

The library wraps your supplied params in `{ asset: params }`.

**Comment by ilrein** [comment]
Works like a charm. Thanks!

**Comment by scgupta208** [comment]
How to get single assest details

 ```
const assestDetails = await shopify.asset.get(themeId, {
            asset: { key: "snippets/price-style.liquid" },
            // asset: { key: "snippets/price-style.liquid" },
          });
```

but it wont work
