### ISSUE TITLE
Cannot Delete RecurringCharge

### ISSUE THREAD

**Issue by ilrein** [MONEI/Shopify-api-node#147]
Hello,

I am attempting to delete a RecurringCharge (create method works just fine). Here's my serverside code:

```
/**
   * Remove a RecurringCharge
   * @type {Shopify}
   */
  app.post('/api/charge/delete', (req, res) => {
    const shopify = new Shopify({ shopName: `${req.body.shopName}`, accessToken: req.body.accessToken });

    console.log(req.body.chargeId);

    shopify.recurringApplicationCharge.delete(req.body.chargeId)
    .then(
      response => {
        console.log('response', response);
        res.status(200);
      },
      err => {
        console.log('error', err);
        res.status(500).json({ err });
      }
    )
  });
```

Alas, here's the console logged response (422 error):

```
7370158
error { HTTPError: Response code 422 (Unprocessable Entity)
    at stream.catch.then.data (/Users/iliareingold/projects/pricing_table/node_modules/got/index.js:182:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
  name: 'HTTPError',
  host: undefined,
  hostname: 'easy-tiles-easy-life.myshopify.com',
  method: 'DELETE',
  path: '/admin/recurring_application_charges/7370158.json',
  protocol: 'https:',
  url: undefined,
  statusCode: 422,
  statusMessage: 'Unprocessable Entity',
  headers: 
   { server: 'nginx',
     date: 'Fri, 17 Nov 2017 04:28:28 GMT',
     'content-type': 'application/json; charset=utf-8',
     'transfer-encoding': 'chunked',
     connection: 'close',
     'x-sorting-hat-podid': '20',
     'x-sorting-hat-podid-cached': '0',
     'x-sorting-hat-shopid': '21756335',
     'x-sorting-hat-section': 'pod',
     'x-sorting-hat-shopid-cached': '0',
     'referrer-policy': 'origin-when-cross-origin',
     'x-frame-options': 'DENY',
     'x-shopid': '21756335',
     'x-shardid': '20',
     'x-stats-userid': '0',
     'x-stats-apiclientid': '1878414',
     'x-stats-apipermissionid': '385155093',
     http_x_shopify_shop_api_call_limit: '2/40',
     'x-shopify-shop-api-call-limit': '2/40',
     'strict-transport-security': 'max-age=7889238',
     'x-request-id': '8702b664-dca9-4bc5-a94d-9ad699ae59dc',
     'content-security-policy': 'default-src \'self\' data: blob: \'unsafe-inline\' \'unsafe-eval\' https://* shopify-pos://*; block-all-mixed-content; child-src \'self\' https://* shopify-pos://*; connect-src \'self\' wss://* https://*; script-src https://cdn.shopify.com https://checkout.shopifycs.com https://js-agent.newrelic.com https://bam.nr-data.net https://dme0ih8comzn4.cloudfront.net https://api.stripe.com https://mpsnare.iesnare.com https://appcenter.intuit.com https://www.paypal.com https://maps.googleapis.com https://stats.g.doubleclick.net https://www.google-analytics.com https://visitors.shopify.com https://v.shopify.com https://widget.intercom.io https://js.intercomcdn.com \'self\' \'unsafe-inline\' \'unsafe-eval\'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=destroy&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Frecurring_application_charges&source%5Bsection%5D=admin_api&source%5Buuid%5D=8702b664-dca9-4bc5-a94d-9ad699ae59dc',
     'x-content-type-options': 'nosniff',
     'x-download-options': 'noopen',
     'x-permitted-cross-domain-policies': 'none',
     'x-xss-protection': '1; mode=block; report=/xss-report?source%5Baction%5D=destroy&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Frecurring_application_charges&source%5Bsection%5D=admin_api&source%5Buuid%5D=8702b664-dca9-4bc5-a94d-9ad699ae59dc',
     'x-dc': 'ash' } }
::ffff:127.0.0.1 - - [17/Nov/2017:04:28:28 +0000] "POST /api/charge/delete HTTP/1.1" 500 2275 430.210 ms
```

and if you are curious as to the clientside code that makes the request...

```
fetch('/api/charge/delete', {
          headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' },
          method: 'POST',
          body: JSON.stringify({
            shopName,
            accessToken,
            chargeId: json.result[0].id
          })
        })
        .then(response => response.json())
        .then(json => {
          // console.log('removing charge...', json);
        })
        .catch(e => e);
```

Am I making a syntax error somewhere?

**Comment by lpinca** [comment]
It looks legit, does the response body include any details? You can get it from the error object:

```js
console.log(err.response.body);
```

**Comment by ilrein** [comment]
Aye, thanks for the tip!

Now it makes a lot more sense, the msg is:

```{ errors: 'Charges must have an \'active\' status before they can be cancelled.' }```

Which would explain a lot, as I'm just using the ```test: true``` for the charges. 

Thanks!
