### ISSUE TITLE
Error message not returned while creating a product with no title

### ISSUE THREAD

**Issue by fredddy123** [MONEI/Shopify-api-node#183]
`shopifyApiNode.product.create` fails with this error:
```
Error: Response code 422 (Unprocessable Entity)
    at stream.catch.then.data (/home/fredddy123/projects/elasticio/components/shopify-component/node_modules/got/index.js:373:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'HTTPError',
  host: undefined,
  hostname: 'fredddy123store.myshopify.com',
  method: 'POST',
  path: '/admin/products.json',
  protocol: 'https:',
  url: undefined,
  statusCode: 422,
  statusMessage: 'Unprocessable Entity',
  headers: 
   { server: 'nginx',
     date: 'Tue, 24 Apr 2018 13:36:52 GMT',
     'content-type': 'application/json; charset=utf-8',
     'transfer-encoding': 'chunked',
     connection: 'close',
     'x-sorting-hat-podid': '43',
     'x-sorting-hat-podid-cached': '0',
     'x-sorting-hat-shopid': '2406285356',
     'x-sorting-hat-section': 'pod',
     'x-sorting-hat-shopid-cached': '0',
     'referrer-policy': 'origin-when-cross-origin',
     'x-frame-options': 'DENY',
     'x-shopid': '2406285356',
     'x-shardid': '43',
     'x-stats-userid': '0',
     'x-stats-apiclientid': '2379034',
     'x-stats-apipermissionid': '48514039852',
     http_x_shopify_shop_api_call_limit: '1/40',
     'x-shopify-shop-api-call-limit': '1/40',
     'x-request-id': '7835fd02-fddd-412b-98a7-e28399b5009a',
     'content-security-policy': 'default-src \'self\' data: blob: \'unsafe-inline\' \'unsafe-eval\' https://* shopify-pos://*; block-all-mixed-content; child-src \'self\' https://* shopify-pos://*; connect-src \'self\' wss://* https://*; script-src https://cdn.shopify.com https://checkout.shopifycs.com https://js-agent.newrelic.com https://bam.nr-data.net https://dme0ih8comzn4.cloudfront.net https://api.stripe.com https://mpsnare.iesnare.com https://appcenter.intuit.com https://www.paypal.com https://maps.googleapis.com https://stats.g.doubleclick.net https://www.google-analytics.com https://visitors.shopify.com https://v.shopify.com https://widget.intercom.io https://js.intercomcdn.com \'self\' \'unsafe-inline\' \'unsafe-eval\'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=create&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fproducts&source%5Bsection%5D=admin_api&source%5Buuid%5D=7835fd02-fddd-412b-98a7-e28399b5009a',
     'x-content-type-options': 'nosniff',
     'x-download-options': 'noopen',
     'x-permitted-cross-domain-policies': 'none',
     'x-xss-protection': '1; mode=block; report=/xss-report?source%5Baction%5D=create&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fproducts&source%5Bsection%5D=admin_api&source%5Buuid%5D=7835fd02-fddd-412b-98a7-e28399b5009a',
     'x-dc': 'ash,gcp-us-east1',
     via: '1.1 google',
     'alt-svc': 'clear' } }
```

if add `console.log('data:', data);` in line 356 in `node_modules/got/index.js`, this error message will be logged:
```
data: {"errors":{"title":["can't be blank"]}}
```

**Comment by lpinca** [comment]
Use `err.response.body`.
