### ISSUE TITLE
Pagination 

### ISSUE THREAD

**Issue by geodyne** [MONEI/Shopify-api-node#188]
The shopify api returns a maximum of 250 objects eg. products.

Does this library handle pagination and make multiple api calls if required? 

There is 'limit' parameter while making a request to get a maximum of N items , but how do we retrieve the next N?

I didn't find answers to this in documentation.

**Comment by lpinca** [comment]
You can use `page` or `since_id`. Get page x, then page x+1, then x+2, etc or get page x, save the biggest id returned and then make a new request with `since_id` set to that value.

This library does not do this automatically.

**Comment by toddheslin** [comment]
Here's how I do it for orders, hopefully the factory pattern isn't too confusing and you can figure out the logic. I essentially have a shopify factory and create these services functions using this library.

Say this module is required as `getShopifyOrders`, I would call it like this:
`const orders = await getShopifyOrders(shopify)(date)`
Where `date` would be the appropriate timestamp format.

```
const { divide, ceil } = require('lodash')
const getShopifyOrderCount = require('./count-orders')

module.exports = shopify => async since => {
	const params = {
		status: 'any',
		financial_status: 'any',
		fulfillment_status: 'any',
		limit: 250
	}
	if (since) params.updated_at_min = since // otherwise get everything

	const orderCount = await getShopifyOrderCount(shopify)(since)

	let pageCount = ceil(divide(orderCount, params.limit))

	const orders = []
	while (pageCount > 0) {
		const pageParams = Object.assign({}, params, { page: pageCount })
		const order = shopify.order.list(pageParams)
		orders.push(order)
		pageCount--
	}
	return Promise.all(orders)
}
```

**Comment by SeanoNET** [comment]
Hi,

Sorry to open an old thread. I am trying to implement @toddheslin async function for getting all products. 

```
const getShopifyProducts = require('./getShopifyProducts')
var products = await getShopifyProducts(shopify);
console.log('Products array count' + products.length);
```
Module getShopifyProducts.js:
```
const perPage = 50;
module.exports = async shopify => {
	const params = {
		limit: perPage
	}
    shopify.product.count().then(productCount => { 
        let pageCount = Math.ceil(productCount/perPage);
        console.log(`Total products: ${productCount} pages: ${pageCount}`);
        const products = []

        while (pageCount > 0) {
            const pageParams = Object.assign({}, params, { page: pageCount })
            const product = shopify.product.list(pageParams)
            products.push(product)
            pageCount--
        }
        return Promise.all(products)
    });
}
```

However i am getting the following error:
> var products = await getShopifyProducts(shopify);
>                ^^^^^
> 
> SyntaxError: await is only valid in async function
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Module._compile (module.js:616:28)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:191:16)
>     at bootstrap_node.js:612:3

if i print the function `console.log(getShopifyProducts)` - i get a async function result: 

> [AsyncFunction]

I am relatively new to async/await and Node it self. If you could give me any pointers i would appreciate it.

**Comment by lpinca** [comment]
@SeanoNET you can only use `await` from the inside of an async function. An async function returns a promise so in your example you can use:

```js
getShopifyProducts(shopify).then((products) => {
  // Work with your products.
});
```

or you can do something like this:

```js
(async () => {
  const products = await getShopifyProducts(shopify);
})();
```

**Comment by SeanoNET** [comment]
Ahh, of course, thanks for that. Now i am having issues with the `shopify.product.count().then(productCount => {` promise returning before `Promise.all(products)`. But i can work through this.

Thanks for the quick response!
