### ISSUE TITLE
 { HTTPError: Response code 401 (Unauthorized)

### ISSUE THREAD

**Issue by WapiMukki** [MONEI/Shopify-api-node#211]
Hi
 I have error
{ HTTPError: Response code 401 (Unauthorized)
2018-07-30T21:43:31.513705+00:00 app[web.1]: at stream.catch.then.data (/app/node_modules/got/index.js:386:13)
2018-07-30T21:43:31.513707+00:00 app[web.1]: at <anonymous>
2018-07-30T21:43:31.513712+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:188:7)
2018-07-30T21:43:31.513714+00:00 app[web.1]: name: 'HTTPError',
2018-07-30T21:43:31.513715+00:00 app[web.1]: host: undefined,
2018-07-30T21:43:31.513717+00:00 app[web.1]: hostname: 'mystore.myshopify.com',
2018-07-30T21:43:31.513718+00:00 app[web.1]: method: 'GET',
2018-07-30T21:43:31.513720+00:00 app[web.1]: path: '/admin/products.json?limit=5',
2018-07-30T21:43:31.513722+00:00 app[web.1]: protocol: 'https:',
2018-07-30T21:43:31.513723+00:00 app[web.1]: url: undefined,
2018-07-30T21:43:31.513725+00:00 app[web.1]: statusCode: 401,
2018-07-30T21:43:31.513727+00:00 app[web.1]: statusMessage: 'Unauthorized',

code:

 const shopify = new  Shopify({
        shopName: shop,
        accessToken: accessToken,
       });

  shopify.product.list({ limit: 5 })
  .then(products => console.log(products))
  .catch(err => console.error(err));

**Comment by lpinca** [comment]
The token you are using is probably no longer valid.

**Comment by lpinca** [comment]
Closing due to inactivity.

**Comment by mobcoder-deepanshu** [comment]
@ghost

> Hi
> I have error
> { HTTPError: Response code 401 (Unauthorized)
> 2018-07-30T21:43:31.513705+00:00 app[web.1]: at stream.catch.then.data (/app/node_modules/got/index.js:386:13)
> 2018-07-30T21:43:31.513707+00:00 app[web.1]: at
> 2018-07-30T21:43:31.513712+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:188:7)
> 2018-07-30T21:43:31.513714+00:00 app[web.1]: name: 'HTTPError',
> 2018-07-30T21:43:31.513715+00:00 app[web.1]: host: undefined,
> 2018-07-30T21:43:31.513717+00:00 app[web.1]: hostname: 'mystore.myshopify.com',
> 2018-07-30T21:43:31.513718+00:00 app[web.1]: method: 'GET',
> 2018-07-30T21:43:31.513720+00:00 app[web.1]: path: '/admin/products.json?limit=5',
> 2018-07-30T21:43:31.513722+00:00 app[web.1]: protocol: 'https:',
> 2018-07-30T21:43:31.513723+00:00 app[web.1]: url: undefined,
> 2018-07-30T21:43:31.513725+00:00 app[web.1]: statusCode: 401,
> 2018-07-30T21:43:31.513727+00:00 app[web.1]: statusMessage: 'Unauthorized',
> 
> code:
> 
> const shopify = new Shopify({
> shopName: shop,
> accessToken: accessToken,
> });
> 
> shopify.product.list({ limit: 5 })
> .then(products => console.log(products))
> .catch(err => console.error(err));

same error mine.How to resolve this error.
