### ISSUE TITLE
InventoryLevel.set() throws "TypeError: The `body` option must be a plain Object or Array when the `form` or `json` option is used` error"

### ISSUE THREAD

**Issue by dossy** [MONEI/Shopify-api-node#248]
I'm trying to set the inventory level of a product using:

```js
api_from.inventoryLevel.set({ location_id: 18948653126, inventory_item_id: 19665570725958, available: 99 }).then(console.log)
```

which results in the following error:

```
TypeError: The `body` option must be a plain Object or Array when the `form` or `json` option is used
    at normalizeArguments (.../node_modules/got/index.js:574:10)
    at got (.../node_modules/got/index.js:645:26)
    at Shopify.request (.../node_modules/shopify-api-node/index.js:122:10)
    at shift (.../node_modules/stopcock/index.js:95:18)
    at Promise (.../node_modules/stopcock/index.js:108:7)
    at new Promise (<anonymous>)
    at Shopify.limiter [as request] (.../node_modules/stopcock/index.js:102:12)
    at InventoryLevel.set (.../node_modules/shopify-api-node/resources/inventory-level.js:72:23)
```

Relevant version information:

```
├─┬ shopify-api-node@2.15.2
│ ├── got@8.3.2
│ ├── lodash@4.17.11 deduped
│ ├── qs@6.5.2
│ └── stopcock@1.0.0
```

**Comment by dossy** [comment]
Interesting:

```
$ node
> require('@sindresorhus/is').plainObject({ test: 123 })
true

$ node -e "require('repl').start('repl> ')"
repl> require('@sindresorhus/is').plainObject({ test: 123 })
false
```
