### ISSUE TITLE
401(UnAuthorized Error.)How it can be resolved?

### ISSUE THREAD

**Issue by mobcoder-deepanshu** [MONEI/Shopify-api-node#315]
Hi I have error { HTTPError: Response code 401 (Unauthorized) 2018-07-30T21:43:31.513705+00:00 app[web.1]: at stream.catch.then.data (/app/node_modules/got/index.js:386:13) 2018-07-30T21:43:31.513707+00:00 app[web.1]: at 2018-07-30T21:43:31.513712+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:188:7) 2018-07-30T21:43:31.513714+00:00 app[web.1]: name: 'HTTPError', 2018-07-30T21:43:31.513715+00:00 app[web.1]: host: undefined, 2018-07-30T21:43:31.513717+00:00 app[web.1]: hostname: 'mystore.myshopify.com', 2018-07-30T21:43:31.513718+00:00 app[web.1]: method: 'GET', 2018-07-30T21:43:31.513720+00:00 app[web.1]: path: '/admin/products.json?limit=5', 2018-07-30T21:43:31.513722+00:00 app[web.1]: protocol: 'https:', 2018-07-30T21:43:31.513723+00:00 app[web.1]: url: undefined, 2018-07-30T21:43:31.513725+00:00 app[web.1]: statusCode: 401, 2018-07-30T21:43:31.513727+00:00 app[web.1]: statusMessage: 'Unauthorized', code:

const shopify = new Shopify({ shopName: shop, accessToken: accessToken, }); shopify.user.current() .then(data => console.log(data)) .catch(err => console.error(err));

**Comment by lpinca** [comment]
Verify that you accessToken is valid.

**Comment by mobcoder-deepanshu** [comment]
> Verify that you access token is valid.

How it can be verify? Is there any steps to verify token.Please tell me.

**Comment by lpinca** [comment]
Follow these guides:

- https://help.shopify.com/en/api/getting-started/authentication/private-authentication#generate-private-app-credentials
- https://help.shopify.com/en/api/getting-started/authentication/oauth

**Comment by lpinca** [comment]
Closing due to inactivity.
