### ISSUE TITLE
(node:143828) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by fancydev18** [MONEI/Shopify-api-node#323]
Hello,

Using this lib with node 12 gives
(node:143828) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

https://stackoverflow.com/questions/56697360/how-to-fix-node12388-dep0066-deprecationwarning-outgoingmessage-prototype

 instead of using obj._headers, use obj.getHeaders() to get the headers object. So replace the property name "._headers" with the function ".getHeaders()". Same results using either one except using the function is the supported method and removes the deprecation warning

**Comment by lpinca** [comment]
This only happens when running tests right?

**Comment by fancydev18** [comment]
> This only happens when running tests right? 
No, using the library with node 12 with an app.

**Comment by lpinca** [comment]
It's `got` then, updating it means dropping support for Node.js < 8.

**Comment by Maxim-Mazurok** [comment]
> It's `got` then, updating it means dropping support for Node.js < 8.

Let's do this then, why not? I'm trying to get `inventoryLevel.list()` and it fails with the same error.

**Comment by Maxim-Mazurok** [comment]
BTW, updating `got` to `9.6.0` gives this error:

```
GotError [HTTPError]: Response code 422 (Unprocessable Entity)
    at EventEmitter.<anonymous> (/home/maxim/IdeaProjects/emons-shopify-integration/node_modules/shopify-api-node/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'HTTPError',
  host: undefined,
  hostname: 'xxxxxxxxxxxxx.myshopify.com',
  method: 'GET',
  path: '/admin/inventory_levels.json',
  socketPath: undefined,
  protocol: 'https:',
  url: undefined,
  gotOptions: {
    path: '/admin/inventory_levels.json',
    protocol: 'https:',
    retry: {
      retries: [Function],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set],
      maxRetryAfter: 60000
    },
    headers: {
      'user-agent': 'shopify-api-node/2.25.1',
      accept: 'application/json',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: false,
    form: false,
    json: true,
    cache: false,
    useElectronNet: false,
    retries: 0,
    method: 'GET',
    auth: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    hostname: 'xxxxxxxxxxxxx.myshopify.com',
    gotTimeout: { request: 60000 }
  },
  statusCode: 422,
  statusMessage: 'Unprocessable Entity',
  headers: {
    date: 'Wed, 20 Nov 2019 20:25:18 GMT',
    'content-type': 'application/json',
    'transfer-encoding': 'chunked',
    connection: 'close',
    'set-cookie': [
      '__cfduid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; expires=Fri, 20-Dec-19 20:25:18 GMT; path=/; domain=.myshopify.com; HttpOnly'
    ],
    'x-sorting-hat-podid': 'xx',
    'x-sorting-hat-shopid': 'xxxxxxxxxx',
    'referrer-policy': 'origin-when-cross-origin',
    'x-frame-options': 'DENY',
    'x-shopid': 'xxxxxxxxxx',
    'x-shardid': 'xx',
    'x-stats-userid': '',
    'x-stats-apiclientid': 'xxxxxxx',
    'x-stats-apipermissionid': '200358396000',
    'x-shopify-api-terms': 'By accessing or using the Shopify API you agree to the Shopify API License and Terms of Use at https://www.shopify.com/legal/api-terms',
    http_x_shopify_shop_api_call_limit: '1/40',
    'x-shopify-shop-api-call-limit': '1/40',
    'x-shopify-api-version': '2019-04',
    'strict-transport-security': 'max-age=7889238',
    'x-shopify-stage': 'production',
    'content-security-policy': "default-src 'self' data: blob: 'unsafe-inline' 'unsafe-eval' https://* shopify-pos://*; block-all-mixed-content; child-src 'self' https://* shopify-pos://*; connect-src 'self' wss://* https://*; frame-ancestors 'none'; img-src 'self' data: blob: https:; script-src https://cdn.shopify.com https://cdn.shopify.cn https://checkout.shopifycs.com https://js-agent.newrelic.com https://bam.nr-data.net https://api.stripe.com https://mpsnare.iesnare.com https://appcenter.intuit.com https://www.paypal.com https://js.braintreegateway.com https://c.paypal.com https://maps.googleapis.com https://www.google-analytics.com https://v.shopify.com https://widget.intercom.io https://js.intercomcdn.com 'self' 'unsafe-inline' 'unsafe-eval'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=index&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Finventory_levels&source%5Bsection%5D=admin_api&source%5Buuid%5D=bf56ea32-884c-4fb4-ba65-cf972a88fb2f",
    'x-content-type-options': 'nosniff',
    'x-download-options': 'noopen',
    'x-permitted-cross-domain-policies': 'none',
    'x-xss-protection': '1; mode=block; report=/xss-report?source%5Baction%5D=index&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Finventory_levels&source%5Bsection%5D=admin_api&source%5Buuid%5D=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'x-dc': 'gcp-us-east1,gcp-us-central1,gcp-us-central1',
    'x-request-id': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'cf-cache-status': 'DYNAMIC',
    'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
    server: 'cloudflare',
    'cf-ray': '538d2702bcb5822f-KBP'
  },
  body: ''
}
```

**Comment by lpinca** [comment]
There is a major version bump between 8 and 9. There are breaking changes. It is expected.

**Comment by Maxim-Mazurok** [comment]
Oh, never mind, fixed that by adding required params, sorry.

Right, so there's a new major library release planned?

**Comment by lpinca** [comment]
Perhaps. Anyway this is just a warning, it does not break anything.
