### ISSUE TITLE
Shopify.customer.search `startsWith` error

### ISSUE THREAD

**Issue by builtbylane** [MONEI/Shopify-api-node#334]
getting the following error when using v3 node v11

```javascript
Shopify.customer.search({email: 'test@gmail.com'});
```

```bash
Cannot read property 'startsWith' of undefined {"name":"RequestError","stack":"GotError: Cannot read property 'startsWith' of undefined
    at get ([PROJECT]/node_modules/got/dist/source/request-as-event-emitter.js:196:27)
    at urlToOptions (internal/url.js:1260:28)
    at Object.request (https.js:293:15)
    at Object.<anonymous> ([PROJECT]/node_modules/agent-base/patch-core.js:25:22)
    at Object.request ([PROJECT]/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20)
    at get ([PROJECT]/node_modules/got/dist/source/request-as-event-emitter.js:193:43)"}
```

seems like it might be related to https://github.com/sindresorhus/got/issues/998. downgrading to v2 solves for now

**Comment by lpinca** [comment]
According to the linked issue, the problem was fixed in `got@10.2.0`. Did you try to update it?

**Comment by dangreaves** [comment]
I manually upgraded to `got@10.2.0`, also getting this exact same error.

**Comment by darekg11** [comment]
Experiencing the same but with different endpoint `POST /webhooks`.

**Comment by lpinca** [comment]
I'm going to close this since there is nothing actionable to do here.
