### ISSUE TITLE
Unable to use after update to 3.1.0

### ISSUE THREAD

**Issue by pociej** [MONEI/Shopify-api-node#339]
I just updated package to lastest version 3.1.0 and just single line of code 

```import Shopify from 'shopify-api-ode'``` 

throws this : 

grzegorzs-Mac-mini:shopify_api_bug_replication grzegorz$ babel-node index.js
internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'Function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function
    at Object.promisify (internal/util.js:209:11)
    at Object.<anonymous> (/Users/grzegorz/Projects/playground/shopify_api_bug_replication/node_modules/got/dist/source/get-response.js:8:25)
    at Module._compile (module.js:660:30)
    at Module._compile (/Users/grzegorz/.nvm/versions/node/v9.3.0/lib/node_modules/@babel/node/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:671:10)
    at Object.newLoader [as .js] (/Users/grzegorz/.nvm/versions/node/v9.3.0/lib/node_modules/@babel/node/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)

**Comment by pociej** [comment]
EDIT : with newest node version ( 12.14.1  ) it works.
