### ISSUE TITLE
Syntax error after upgrading to 3.2.0 Unexpected token *

### ISSUE THREAD

**Issue by pklitscher** [MONEI/Shopify-api-node#348]
I am deploying `shopify-api-node` to Firebase cloud functions. I have been using version *2.18.0* with no problems. I wanted to upgrade to use pagination. I upgraded to *3.2.0*  and started receiving the error below. I have rolled back to *2.24.0* and is now working again (with pagination)

```
Detailed stack trace: /srv/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/node_modules/got/dist/source/index.js:7:18)
```

Thank you your work :) Love it

**Comment by lpinca** [comment]
Version 3.x requires Node.js >= 10.

**Comment by pklitscher** [comment]
> Version 3.x requires Node.js >= 10.

Ahhhh thank you. @lpinca
