### ISSUE TITLE
after the version 3 The Firebase deploy return an error

### ISSUE THREAD

**Issue by Bamorem** [MONEI/Shopify-api-node#351]
I was using the version 2.5.1 and everything was working perfectly. but since I received an email from shopify to tell me that my api request was out of date I wanted to upgrade the version of the api-node but from the version 3 and more my firebase deploy doesn't work anymore ...
And I have only this issue with the new version.

Someone can help me ?
=====
 Deployment error.
Function failed on loading user code. Error message: Code in file lib/index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: /srv/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/node_modules/got/dist/source/index.js:7:18)

**Comment by lpinca** [comment]
See https://github.com/MONEI/Shopify-api-node/issues/348
