### ISSUE TITLE
Generate Function Error when deploying to firebase

### ISSUE THREAD

**Issue by robotshatemonkeys** [MONEI/Shopify-api-node#381]
I cannot use the library with Firebase. Firebase runs on Node 8. 
As importing the library fails: 
Detailed stack trace: /srv/node_modules/got/dist/source/create.js:133
    const paginateEach = (async function* (url, options) {
                                  
SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/node_modules/got/dist/source/index.js:7:18)

**Comment by lpinca** [comment]
https://github.com/MONEI/Shopify-api-node/blob/3.3.2/package.json#L10
