### ISSUE TITLE
Product title can't be blank

### ISSUE THREAD

**Issue by james-em** [MONEI/Shopify-api-node#403]
===== FIXED =====
This is my mistake, I though I had to wrap the payload within product just like the API documentation.

**Explanation**

I am unable to create a product using this library. Odly, taking the same exact payload in a REST Client works.

**Error**

```
HTTPError: Response code 422 (Unprocessable Entity)
    at onResponse (/Users/james/Projects/RPPShopifySync/node_modules/shopify-api-node/node_modules/got/dist/source/as-promise/index.js:142:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1596730474391,
    socket: 1596730474391,
    lookup: 1596730474392,
    connect: 1596730474408,
    secureConnect: 1596730474427,
    upload: 1596730474427,
    response: 1596730474650,
    end: 1596730474650,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: 16,
      tls: 19,
      request: 0,
      firstByte: 223,
      download: 0,
      total: 259
    }
  }
} { errors: { title: [ "can't be blank" ] } }
```

**How to reproduce**

```
await this.shopify.product.create({ product: { ...product } });
```

Payload 
```
If I print { product: { ...product } }, I get
{
    "product": {
        "title": "KEEN GARÇON ESPADRILLE LACÉ",
        "body_html": "",
        "vendor": "KEEN CANADA",
        "tags": "GARÇON, ESPADRILLE",
        "published_at": null,
        "options": [
            {
                "name": "grandeur"
            },
            {
                "name": "couleur"
            },
            {
                "name": "largeur"
            }
        ],
        "variants": [
            {
                "sku": "1019824",
                "barcode": "4850000314647",
                "price": 75,
                "inventory_management": "shopify",
                "inventory_policy": "deny",
                "option1": "2",
                "option2": "GRIS/ROUGE",
                "option3": "M"
            },
            {
                "sku": "1019824",
                "barcode": "4850000314654",
                "price": 75,
                "inventory_management": "shopify",
                "inventory_policy": "deny",
                "option1": "3",
                "option2": "GRIS/ROUGE",
                "option3": "M"
            },
            {
                "sku": "1019824",
                "barcode": "4850000314685",
                "price": 75,
                "inventory_management": "shopify",
                "inventory_policy": "deny",
                "option1": "6",
                "option2": "GRIS/ROUGE",
                "option3": "M"
            }
        ]
    }
}
```

**Comment by alessandroMaffle** [comment]
Hi, excuse me, but how did you solve it?

**Comment by jamesst20** [comment]
> Hi, excuse me, but how did you solve it?

The payload was wrapped under the product key by accident:

```
{
    "product": {
        "title": "KEEN GARÇON ESPADRILLE LACÉ",
         ...
     }
}
```

vs

```
{
     "title": "KEEN GARÇON ESPADRILLE LACÉ",
       ...
}
```

**Comment by alessandroMaffle** [comment]
Thank you very much =)
