### ISSUE TITLE
ProductListing.list() return 403 error code

### ISSUE THREAD

**Issue by nguyennghia9222** [MONEI/Shopify-api-node#410]
Hi guys,
I face the issue on Product Listing API. Could you please have a look at the error stack below? Thanks
```
const shopifyClient = new Shopify.ShopifyClient(...);
shopifyClient.productListing.list().then(console.log);
```
```
(node:382657) UnhandledPromiseRejectionWarning: HTTPError: Response code 403 (Forbidden)
    at onResponse (/home/.../node_modules/shopify-api-node/node_modules/got/dist/source/as-promise/index.js:142:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:382657) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:382657) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Version Used: 3.4.4

**Comment by Salman-Arshad** [comment]
Same issue

**Comment by lpinca** [comment]
The server is returning 403, probably because the token used does not have sufficient permissions.

**Comment by nguyennghia9222** [comment]
Thanks @lpinca.
