### ISSUE TITLE
RequestError: getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by rounsmith** [MONEI/Shopify-api-node#625]
Hello , all

Today while i was trying to update price on a product i was getting the above error.

Full error code below:

 RequestError: getaddrinfo EAI_AGAIN 
     at ClientRequest.<anonymous> (/workspace/node_modules/got/dist/source/core/index.js:970:111)
     at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.origin.emit (/workspace/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
  at TLSSocket.socketErrorListener (node:_http_client:494:9)
     at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
     at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
   code: 'EAI_AGAIN',
   timings: {
     start: 1690920544698,
   socket: 1690920544698,
  lookup: 1690920554703,
    connect: undefined,
     secureConnect: undefined,
   upload: undefined,
   response: undefined,
    end: undefined,
    error: 1690920554703,
    abort: undefined,
    phases: {
      wait: 0,
   dns: 10005,
     tcp: undefined,
       tls: undefined,
     request: undefined,
     firstByte: undefined,
     download: undefined,
     total: 10005
    }
   }
 }

**Comment by lpinca** [comment]
This is a DNS lookup timeout error. It is not an issue in the library.
